services:
  db:
    image: 'mysql:lts'
    environment:
      - 'TZ=Asia/Seoul'
      - 'MYSQL_DATABASE=dornol'
      - 'MYSQL_ROOT_PASSWORD=1234'
    ports:
      - "3306:3306"

  redis:
    image: 'redis:latest'
    environment:
      - 'TZ=Asia/Seoul'
    ports:
      - "6379:6379"
